## Before you start

We recommend running this notebook on Google Colab to avoid having to install dependencies.

Note:

*   You can use any functions provided in the numpy, but not the functions in scipy.
*   You should use *numpy.linalg.solve()* to invert a matrix for more numerical stable results rather than *numpy.linalg.inv()*. Refer to [link](http://gregorygundersen.com/blog/2020/12/09/matrix-inversion/) for more details.
* Try to avoid for-loops. Refer to [link](https://www.learndatasci.com/tutorials/applied-introduction-to-numpy-python-tutorial/) for more details.


## Load packages

In [ ]:
import numpy as np
from scipy import stats

## Part c: Computing optimal $\vec{\gamma}$


Implement the function below, which defines the input data matrix $\mathbf{A}$ (variable A) and the vector of desired outputs $\vec{y}$ (variable y). Calculate the optimal $\vec{\gamma}$ (variable gamma_star). All the variables should be the type of np.float64.

In [ ]:
def part_2c(l, odd_indexed_sum):
  """
  l: Number of possible outcomes.
  odd_indexed_sum: Sum of the probability masses of Q at odd-indexed outcomes
  return: Input data matrix A, desired outputs y, and optimal parameters gamma_star
  """
  # TODO: Assign the variables below appropriately

  A = np.zeros((2,l))
  for i in range (l):
    A[0][i] = 1
    #note that in assignment, it's gamma 1,2,3,4...10 so 1,0,1,0... for A[i]
    if (i % 2 == 0):
      A[1][i] = 1

  y = np.array([[1],
                [odd_indexed_sum]])
  
  identity = np.identity(l)
  gamma_star = np.linalg.solve((A.T@A+identity), A.T@y)

  return A, y, gamma_star

l = 10
odd_indexed_sum = 0.8

A, y, gamma_star = part_2c(l, odd_indexed_sum)

# Do not modify the lines below
assert(isinstance(A, np.ndarray))
assert(A.dtype == np.float64)
assert(isinstance(y, np.ndarray))
assert(y.dtype == np.float64)
assert(isinstance(gamma_star, np.ndarray))
assert(gamma_star.dtype == np.float64)

print("A:\n{}\ny:\n{}\n".format(A, y))
print("gamma_star:\n{}".format(gamma_star))
print("Prediction:\n{}".format(A.dot(gamma_star)))
print("Loss:\n{}".format(np.linalg.norm(y - A.dot(gamma_star))))

A:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
y:
[[1. ]
 [0.8]]

gamma_star:
[[0.14146341]
 [0.04878049]
 [0.14146341]
 [0.04878049]
 [0.14146341]
 [0.04878049]
 [0.14146341]
 [0.04878049]
 [0.14146341]
 [0.04878049]]
Prediction:
[[0.95121951]
 [0.70731707]]
Loss:
0.10473614904187271


## Part e: Computing optimal $\mathrm{vec}(\mathbb{\Gamma})$





Implement the function below, which defines the data matrix $\mathbf{A}$ (variable A) and label vector $\vec{y}$ (variable y). Calculate the optimal $\mathrm{vec}(\mathbb{\Gamma})$ (variable Gamma_star) using the formula derived in part *d*.

Note: The $\vec{p}$, $\vec{q}$, $\{u_i\}_{i=1}^{l}$ and $\{v_j\}_{i=1}^{l}$ are given as the variables p, q, U and V.

In [ ]:
def part_2e(l, p, q, U, V):
  """
  l: Number of possible outcomes.
  p: Probability mass function of P.
  q: Probability mass function of Q.
  U: All possible outcomes of P. 
  V: All possible outcomes of Q. 
  return: Input data matrix A, desired outputs y, and optimal parameters Gamma_star
  """
  # TODO: Assign the variables below appropriately

  A = np.zeros((2*l, l**2))
  for i in range(l):
    for j in range(l):
      A[i][(i*l)+j] = 1.
  for i in range(l):
    for j in range(l):
      A[i+l][(j*l)+i] = 1.

  y = np.concatenate((p,q))

  Gamma_star = np.linalg.solve(((A.T@A)+ np.identity(l**2)), (A.T@y))

  return A, y, Gamma_star

# Do not modify the lines below

U = np.linspace(0, 9, num=10)
V = np.linspace(5, 14, num=10)

# Poisson distributions
p = stats.poisson.pmf(U, mu=4)
q = stats.poisson.pmf(V, mu=10)

# Normalize distributions
p = (p / np.sum(p)).astype(np.float64)
q = (q / np.sum(q)).astype(np.float64)

l = U.shape[0]  # l = 10

A, y, Gamma_star = part_2e(l, p, q, U, V)

assert(isinstance(A, np.ndarray))
assert(A.dtype == np.float64)
assert(isinstance(y, np.ndarray))
assert(y.dtype == np.float64)
assert(isinstance(Gamma_star, np.ndarray))
assert(Gamma_star.dtype == np.float64)

print("A:\n{}\ny:\n{}\n".format(A, y))
print("Gamma_star:\n{}".format(Gamma_star))
print("Prediction:\n{}".format(A.dot(Gamma_star)))
print("Loss:\n{}".format(np.linalg.norm(y - A.dot(Gamma_star))))

A:
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
y:
[0.01846581 0.07386323 0.14772646 0.19696861 0.19696861 0.15757489
 0.10504993 0.06002853 0.03001426 0.01333967 0.04263919 0.07106531
 0.10152187 0.12690234 0.1410026  0.1410026  0.12818418 0.10682015
 0.08216935 0.05869239]

Gamma_star:
[-3.10300917e-03 -5.18816011e-04  2.24996237e-03  4.55727769e-03
  5.83911953e-03  5.83911953e-03  4.67380877e-03  2.73162416e-03
  4.90641911e-04 -1.64362689e-03  1.93312010e-03  4.51731326e-03
  7.28609164e-03  9.59340696e-03  1.08752488e-02  1.08752488e-02
  9.70993803e-03  7.76775342e-03  5.52677118e-03  3.39250238e-03
  8.64795913e-03  1.12321523e-02  1.40009307e-02  1.63082460e-02
  1.75900878e-02  1.75900878e-02  1.64247771e-02  1.44825924e-02
  1.22416102e-02  1.01073414e-02  1.31245185e-02  1.57087116e-02
  1.84774900e-02  2.07848053e-02  2.20666472e-02  2.20666472e-02
  2.09013364e-0

## Part g: Computing optimal $\mathrm{vec}(\mathbb{\Gamma})$

Write code below that defines the data matrix $\mathbf{A}$ (variable A), label vector $\vec{y}$ (variable y) and distance vector $\vec{\lambda}$ (variable la). Calculate the optimal $\mathrm{vec}(\mathbb{\Gamma})$ (variable Gamma_star) with those variables base on part *f*.

Note:

*   The $\vec{p}$, $\vec{q}$, $\{u_i\}_{i=1}^{l}$ and $\{v_j\}_{i=1}^{l}$ are given as the variables p, q, U and V.
*   The distance between $u_i$ and $v_j$ is defined in the given function *distance_between()*, for example distance between $u_i = 2$ and $v_j = 5$ is $\vert 2 - 5 \vert$.



In [ ]:
def part_2g(l, p, q, U, V, D):
  """
  l: Number of possible outcomes.
  p: Probability mass function of P.
  q: Probability mass function of Q.
  U: All possible outcomes of P. 
  V: All possible outcomes of Q. 
  D: Matrix of distances between U and V. 
  return: Input data matrix A, desired outputs y, distance vector la and optimal parameters Gamma_star
  """
  # TODO: Assign to the variables below appropriately

  d = D.flatten()

  A = np.zeros((2*l, l**2))
  for i in range(l):
    for j in range(l):
      A[i][(i*l)+j] = 1
  for i in range(l):
    for j in range(l):
      A[i+l][(j*l)+i] = 1

  y = np.concatenate((p,q))

  la = np.column_stack(D.flatten())

  Gamma_star = np.linalg.solve(((A.T@A)+ (la.T.dot(la)@np.identity(l**2))), (A.T@y))

  return A, y, la, Gamma_star

# Do not modify the lines below

def distance_between(U, V):
    return np.abs(U[:,np.newaxis] - V[np.newaxis,:])

U = np.linspace(0, 9, num=10)
V = np.linspace(5, 14, num=10)

# Poisson distributions
p = stats.poisson.pmf(U, mu=4)
q = stats.poisson.pmf(V, mu=10)

# Normalize distributions
p = (p / np.sum(p)).astype(np.float64)
q = (q / np.sum(q)).astype(np.float64)

l = U.shape[0]  # l = 10

D = distance_between(U, V)

A, y, la, Gamma_star = part_2g(l, p, q, U, V, D)

assert(isinstance(A, np.ndarray))
assert(A.dtype == np.float64)
assert(isinstance(y, np.ndarray))
assert(y.dtype == np.float64)
assert(isinstance(la, np.ndarray))
assert(la.dtype == np.float64)
assert(isinstance(Gamma_star, np.ndarray))
assert(Gamma_star.dtype == np.float64)

print("A:\n{}\ny:\n{}\nlambda:\n{}".format(A, y, la.transpose(1, 0)))
print("Gamma_star:\n{}".format(Gamma_star))
print("Prediction:\n{}".format(A.dot(Gamma_star)))
print("Loss:\n{}".format(np.linalg.norm(y - A.dot(Gamma_star))))

A:
[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
y:
[0.01846581 0.07386323 0.14772646 0.19696861 0.19696861 0.15757489
 0.10504993 0.06002853 0.03001426 0.01333967 0.04263919 0.07106531
 0.10152187 0.12690234 0.1410026  0.1410026  0.12818418 0.10682015
 0.08216935 0.05869239]
lambda:
[[ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 3.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 